name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull tinzarpaing/getchup_backend:latest

    - name: Delete Old docker container
      run: sudo docker rm -f getchup_backend-container || true

    - name: Run Docker Container
      env:
        DB_URL: ${{ secrets.DB_URL }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        sudo docker run -d -p 8080:8080 \
          --name getchup_backend-container \
          --restart always \
          -e DB_URL=${{ secrets.DB_URL }} \
          -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          tinzarpaing/getchup_backend \
          pm2-runtime start app.js


