name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull tinzarpaing/getchup_backend:latest
    - name: Delete Old docker container
      run: sudo docker rm -f getchup_backend-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name getchup_backend-container tinzarpaing/getchup_backend
    - name: Copy .env to Docker container
      run: |
        sudo docker cp /home/ubuntu/.env getchup_backend-container:/usr/src/app/.env

